workflows:
  ios-appstore:
    name: iOS App Store
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.voolo.jetx
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.voolo.jetx

    integrations:
      app_store_connect: app-store-connect

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Set up keychain and certificates
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Verify signing settings
        script: |
          xcode-project show-build-settings --project ios/Runner.xcodeproj --scheme Runner | grep -E "CODE_SIGN_STYLE|DEVELOPMENT_TEAM|PROVISIONING_PROFILE_SPECIFIER|PRODUCT_BUNDLE_IDENTIFIER"

      - name: Build signed IPA
        script: |
          flutter build ipa --release --export-method app-store-connect || true

      - name: Export IPA from xcarchive (fallback)
        script: |
          mkdir -p build/ios/ipa
          ARCHIVE_PATH="$(find build/ios/archive -maxdepth 1 -type d -name '*.xcarchive' | head -n 1)"
          if [ -z "$ARCHIVE_PATH" ]; then
            echo "No xcarchive found to export."
            exit 1
          fi

          cat > /tmp/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string>VYJN27MQ6V</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /tmp/ExportOptions.plist

      - name: Validate and collect IPA
        script: |
          echo "Listing iOS build outputs..."
          find build/ios -type f | sed 's|^| - |'

          IPA_PATH="$(find build/ios -type f -name '*.ipa' | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "ERROR: No .ipa file was generated."
            exit 1
          fi

          mkdir -p build/ios/ipa
          cp "$IPA_PATH" build/ios/ipa/Runner.ipa
          echo "IPA ready at build/ios/ipa/Runner.ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
